-- -----------------------------------------------------
-- Schema full-stack-ecommerce
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `full-stack-ecommerce`;

CREATE SCHEMA `full-stack-ecommerce`;
USE `full-stack-ecommerce` ;

-- -----------------------------------------------------
-- Table `full-stack-ecommerce`.`product_category`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `full-stack-ecommerce`.`product_category` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `category_name` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE=InnoDB
AUTO_INCREMENT = 1;

-- -----------------------------------------------------
-- Table `full-stack-ecommerce`.`product`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `full-stack-ecommerce`.`product` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `sku` VARCHAR(255) DEFAULT NULL,
  `name` VARCHAR(255) DEFAULT NULL,
  `description` VARCHAR(255) DEFAULT NULL,
  `unit_price` DECIMAL(13,2) DEFAULT NULL,
  `image_url` VARCHAR(255) DEFAULT NULL,
  `active` BIT DEFAULT 1,
  `units_in_stock` INT(11) DEFAULT NULL,
  `date_created` DATETIME(6) DEFAULT NULL,
  `last_updated` DATETIME(6) DEFAULT NULL,
  `category_id` BIGINT(20) NOT NULL,
  PRIMARY KEY (`id`),
  KEY `fk_category` (`category_id`),
  CONSTRAINT `fk_category` FOREIGN KEY (`category_id`) REFERENCES `product_category` (`id`)
) 
ENGINE=InnoDB
AUTO_INCREMENT = 1;

-- -----------------------------------------------------
-- Categories
-- -----------------------------------------------------
INSERT INTO product_category(category_name) VALUES ('Small Cap');
INSERT INTO product_category(category_name) VALUES ('Mid Cap');
INSERT INTO product_category(category_name) VALUES ('Large Cap');
INSERT INTO product_category(category_name) VALUES ('Gold Funds');



-- -----------------------------------------------------
-- SmallCap
-- -----------------------------------------------------
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('SmallCapFund-1000', 'Quant Small Cap Fund', 'This smallCap includes working examples that you can apply to your own projects. Purchase the smallCap and get started today!', 'assets/images/products/SmallCap/smallCap-1000.png', 1, 100, 14.99, 1, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('SmallCapFund-1001', 'Nippon Small Cap Fund', 'This smallCap includes working examples that you can apply to your own projects. Purchase the smallCap and get started today!', 'assets/images/products/SmallCap/smallCap-1001.png', 1, 100, 20.99, 1, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('SmallCapFund-1002', 'HSBC Small Cap Fund', 'Learn Vue.js at your own pace. This smallCap includes working examples that you can apply to your own projects. Purchase the smallCap and get started today!', 'assets/images/products/SmallCap/smallCap-1002.png', 1, 100, 14.99, 1, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('SmallCapFund-1003', 'HDFC Small Cap Fund', 'This smallCap includes working examples that you can apply to your own projects. Purchase the smallCap and get started today!', 'assets/images/products/SmallCap/smallCap-1003.png', 1, 100, 13.99, 1, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('SmallCapFund-1004', 'Kotak Small Cap Fund', 'This smallCap includes working examples that you can apply to your own projects. Purchase the smallCap and get started today!', 'assets/images/products/SmallCap/smallCap-1004.png', 1, 100, 18.99, 1, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('SmallCapFund-1005', 'Union Small Cap Fund', 'This smallCap includes working examples that you can apply to your own projects. Purchase the smallCap and get started today!', 'assets/images/products/SmallCap/smallCap-1005.png', 1, 100, 23.99, 1, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('SmallCapFund-1006', 'Franklin India  Small Cap Fund', 'This smallCap includes working examples that you can apply to your own projects. Purchase the smallCap and get started today!', 'assets/images/products/SmallCap/smallCap-1006.png', 1, 100, 14.99, 1, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('SmallCapFund-1007', 'Sundaram Small Cap Fund', 'This smallCap includes working examples that you can apply to your own projects. Purchase the smallCap and get started today!', 'assets/images/products/SmallCap/smallCap-1007.png', 1, 100, 16.99, 1, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('SmallCapFund-1008', 'Axis Small Cap Fund', 'This smallCap includes working examples that you can apply to your own projects. Purchase the smallCap and get started today!', 'assets/images/products/SmallCap/smallCap-1008.png', 1, 100, 25.99, 1, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('SmallCapFund-1009', 'SBI Small Cap Fund', 'This smallCap includes working examples that you can apply to your own projects. Purchase the smallCap and get started today!', 'assets/images/products/SmallCap/smallCap-1009.png', 1, 100, 23.99, 1, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('SmallCapFund-1010', 'Aditya Birla Small Cap Fund', 'This smallCap includes working examples that you can apply to your own projects. Purchase the smallCap and get started today!', 'assets/images/products/SmallCap/smallCap-1010.png', 1, 100, 24.99, 1, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('SmallCapFund-1011', 'Bandhan Small Cap Fund', 'This smallCap includes working examples that you can apply to your own projects. Purchase the smallCap and get started today!', 'assets/images/products/SmallCap/smallCap-1011.png', 1, 100, 19.99, 1, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('SmallCapFund-1012', 'BOI Small Cap Fund', 'This smallCap includes working examples that you can apply to your own projects. Purchase the smallCap and get started today!', 'assets/images/products/SmallCap/smallCap-1012.png', 1, 100, 24.99, 1, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('SmallCapFund-1013', 'Canara Small Cap Fund', 'This smallCap includes working examples that you can apply to your own projects. Purchase the smallCap and get started today!', 'assets/images/products/SmallCap/smallCap-1013.png', 1, 100, 19.99, 1, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('SmallCapFund-1014', 'Edeilweiss Small Cap Fund', 'This smallCap includes working examples that you can apply to your own projects. Purchase the smallCap and get started today!', 'assets/images/products/SmallCap/smallCap-1014.png', 1, 100, 22.99, 1, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('SmallCapFund-1015', 'Invesco Small Cap Fund', 'This smallCap includes working examples that you can apply to your own projects. Purchase the smallCap and get started today!', 'assets/images/products/SmallCap/smallCap-1015.png', 1, 100, 22.99, 1, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('SmallCapFund-1016', 'Mahindra Small Cap Fund', 'This smallCap includes working examples that you can apply to your own projects. Purchase the smallCap and get started today!', 'assets/images/products/SmallCap/smallCap-1016.png', 1, 100, 27.99, 1, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('SmallCapFund-1017', 'PGIM Small Cap Fund', 'This smallCap includes working examples that you can apply to your own projects. Purchase the smallCap and get started today!', 'assets/images/products/SmallCap/smallCap-1017.png', 1, 100, 13.99, 1, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('SmallCapFund-1018', 'Tata Small Cap Fund', 'This smallCap includes working examples that you can apply to your own projects. Purchase the smallCap and get started today!', 'assets/images/products/SmallCap/smallCap-1018.png', 1, 100, 26.99, 1, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('SmallCapFund-1019', 'UTI Small Cap Fund', 'This smallCap includes working examples that you can apply to your own projects. Purchase the smallCap and get started today!', 'assets/images/products/SmallCap/smallCap-1019.png', 1, 100, 13.99, 1, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('SmallCapFund-1020', 'ITI Small Cap Fund', 'This smallCap includes working examples that you can apply to your own projects. Purchase the smallCap and get started today!', 'assets/images/products/SmallCap/smallCap-1020.png', 1, 100, 19.99, 1, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('SmallCapFund-1021', 'Motilal Small Cap Fund', 'This smallCap includes working examples that you can apply to your own projects. Purchase the smallCap and get started today!', 'assets/images/products/SmallCap/smallCap-1021.png', 1, 100, 18.99, 1, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('SmallCapFund-1022', 'DSP Small Cap Fund', 'This smallCap includes working examples that you can apply to your own projects. Purchase the smallCap and get started today!', 'assets/images/products/SmallCap/smallCap-1022.png', 1, 100, 26.99, 1, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('SmallCapFund-1023', 'LIC Small Cap Fund', 'This smallCap includes working examples that you can apply to your own projects. Purchase the smallCap and get started today!', 'assets/images/products/SmallCap/smallCap-1023.png', 1, 100, 22.99, 1, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('SmallCapFund-1024', 'ICICI Small Cap Fund', 'This smallCap includes working examples that you can apply to your own projects. Purchase the smallCap and get started today!', 'assets/images/products/SmallCap/smallCap-1024.png', 1, 100, 16.99, 1, NOW());


-- -----------------------------------------------------
-- MidCap
-- -----------------------------------------------------
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('MidCapFund-1000', 'Quant Mid Cap Fund', 'Purchase the MidCap and get started today!', 'assets/images/products/MidCap/MidCap-1000.png', 1, 100, 14.99, 1, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('MidCapFund-1001', 'Nippon Mid Cap Fund', 'Purchase the MidCap and get started today!', 'assets/images/products/MidCap/MidCap-1001.png', 1, 100, 20.99, 1, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('MidCapFund-1002', 'HSBC Mid Cap Fund', 'Learn Vue.js at your own pace. Purchase the MidCap and get started today!', 'assets/images/products/MidCap/MidCap-1002.png', 1, 100, 14.99, 1, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('MidCapFund-1003', 'HDFC Mid Cap Fund', 'Purchase the MidCap and get started today!', 'assets/images/products/MidCap/MidCap-1003.png', 1, 100, 13.99, 1, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('MidCapFund-1004', 'Kotak Mid Cap Fund', 'Purchase the MidCap and get started today!', 'assets/images/products/MidCap/MidCap-1004.png', 1, 100, 18.99, 1, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('MidCapFund-1005', 'Union Mid Cap Fund', 'Purchase the MidCap and get started today!', 'assets/images/products/MidCap/MidCap-1005.png', 1, 100, 23.99, 1, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('MidCapFund-1006', 'Franklin India  Mid Cap Fund', 'Purchase the MidCap and get started today!', 'assets/images/products/MidCap/MidCap-1006.png', 1, 100, 14.99, 1, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('MidCapFund-1007', 'Sundaram Mid Cap Fund', 'Purchase the MidCap and get started today!', 'assets/images/products/MidCap/MidCap-1007.png', 1, 100, 16.99, 1, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('MidCapFund-1008', 'Axis Mid Cap Fund', 'Purchase the MidCap and get started today!', 'assets/images/products/MidCap/MidCap-1008.png', 1, 100, 25.99, 1, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('MidCapFund-1009', 'SBI Mid Cap Fund', 'Purchase the MidCap and get started today!', 'assets/images/products/MidCap/MidCap-1009.png', 1, 100, 23.99, 1, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('MidCapFund-1010', 'Aditya Birla Mid Cap Fund', 'Purchase the MidCap and get started today!', 'assets/images/products/MidCap/MidCap-1010.png', 1, 100, 24.99, 1, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('MidCapFund-1011', 'Bandhan Mid Cap Fund', 'Purchase the MidCap and get started today!', 'assets/images/products/MidCap/MidCap-1011.png', 1, 100, 19.99, 1, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('MidCapFund-1012', 'BOI Mid Cap Fund', 'Purchase the MidCap and get started today!', 'assets/images/products/MidCap/MidCap-1012.png', 1, 100, 24.99, 1, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('MidCapFund-1013', 'Canara Mid Cap Fund', 'Purchase the MidCap and get started today!', 'assets/images/products/MidCap/MidCap-1013.png', 1, 100, 19.99, 1, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('MidCapFund-1014', 'Edeilweiss Mid Cap Fund', 'Purchase the MidCap and get started today!', 'assets/images/products/MidCap/MidCap-1014.png', 1, 100, 22.99, 1, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('MidCapFund-1015', 'Invesco Mid Cap Fund', 'Purchase the MidCap and get started today!', 'assets/images/products/MidCap/MidCap-1015.png', 1, 100, 22.99, 1, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('MidCapFund-1016', 'Mahindra Mid Cap Fund', 'Purchase the MidCap and get started today!', 'assets/images/products/MidCap/MidCap-1016.png', 1, 100, 27.99, 1, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('MidCapFund-1017', 'PGIM Mid Cap Fund', 'Purchase the MidCap and get started today!', 'assets/images/products/MidCap/MidCap-1017.png', 1, 100, 13.99, 1, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('MidCapFund-1018', 'Tata Mid Cap Fund', 'Purchase the MidCap and get started today!', 'assets/images/products/MidCap/MidCap-1018.png', 1, 100, 26.99, 1, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('MidCapFund-1019', 'UTI Mid Cap Fund', 'Purchase the MidCap and get started today!', 'assets/images/products/MidCap/MidCap-1019.png', 1, 100, 13.99, 1, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('MidCapFund-1020', 'ITI Mid Cap Fund', 'Purchase the MidCap and get started today!', 'assets/images/products/MidCap/MidCap-1020.png', 1, 100, 19.99, 1, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('MidCapFund-1021', 'Motilal Mid Cap Fund', 'Purchase the MidCap and get started today!', 'assets/images/products/MidCap/MidCap-1021.png', 1, 100, 18.99, 1, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('MidCapFund-1022', 'DSP Mid Cap Fund', 'Purchase the MidCap and get started today!', 'assets/images/products/MidCap/MidCap-1022.png', 1, 100, 26.99, 1, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('MidCapFund-1023', 'LIC Mid Cap Fund', 'Purchase the MidCap and get started today!', 'assets/images/products/MidCap/MidCap-1023.png', 1, 100, 22.99, 1, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('MidCapFund-1024', 'ICICI Mid Cap Fund', 'Purchase the MidCap and get started today!', 'assets/images/products/MidCap/MidCap-1024.png', 1, 100, 16.99, 1, NOW());


-- -----------------------------------------------------
-- LargeCap
-- -----------------------------------------------------
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('LargeCapFund-1000', 'Quant Large Cap Fund', 'This LargeCap includes working examples that you can apply to your own projects. Purchase the LargeCap and get started today!', 'assets/images/products/LargeCap/largeCap-1000.png', 1, 100, 14.99, 1, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('LargeCapFund-1001', 'Nippon Large Cap Fund', 'This LargeCap includes working examples that you can apply to your own projects. Purchase the LargeCap and get started today!', 'assets/images/products/LargeCap/largeCap-1001.png', 1, 100, 20.99, 1, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('LargeCapFund-1002', 'HSBC Large Cap Fund', 'Learn Vue.js at your own pace. This LargeCap includes working examples that you can apply to your own projects. Purchase the LargeCap and get started today!', 'assets/images/products/LargeCap/largeCap-1002.png', 1, 100, 14.99, 1, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('LargeCapFund-1003', 'HDFC Large Cap Fund', 'This LargeCap includes working examples that you can apply to your own projects. Purchase the LargeCap and get started today!', 'assets/images/products/LargeCap/largeCap-1003.png', 1, 100, 13.99, 1, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('LargeCapFund-1004', 'Kotak Large Cap Fund', 'This LargeCap includes working examples that you can apply to your own projects. Purchase the LargeCap and get started today!', 'assets/images/products/LargeCap/largeCap-1004.png', 1, 100, 18.99, 1, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('LargeCapFund-1005', 'Union Large Cap Fund', 'This LargeCap includes working examples that you can apply to your own projects. Purchase the LargeCap and get started today!', 'assets/images/products/LargeCap/largeCap-1005.png', 1, 100, 23.99, 1, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('LargeCapFund-1006', 'Franklin India  Large Cap Fund', 'This LargeCap includes working examples that you can apply to your own projects. Purchase the LargeCap and get started today!', 'assets/images/products/LargeCap/largeCap-1006.png', 1, 100, 14.99, 1, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('LargeCapFund-1007', 'Sundaram Large Cap Fund', 'This LargeCap includes working examples that you can apply to your own projects. Purchase the LargeCap and get started today!', 'assets/images/products/LargeCap/largeCap-1007.png', 1, 100, 16.99, 1, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('LargeCapFund-1008', 'Axis Large Cap Fund', 'This LargeCap includes working examples that you can apply to your own projects. Purchase the LargeCap and get started today!', 'assets/images/products/LargeCap/largeCap-1008.png', 1, 100, 25.99, 1, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('LargeCapFund-1009', 'SBI Large Cap Fund', 'This LargeCap includes working examples that you can apply to your own projects. Purchase the LargeCap and get started today!', 'assets/images/products/LargeCap/largeCap-1009.png', 1, 100, 23.99, 1, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('LargeCapFund-1010', 'Aditya Birla Large Cap Fund', 'This LargeCap includes working examples that you can apply to your own projects. Purchase the LargeCap and get started today!', 'assets/images/products/LargeCap/largeCap-1010.png', 1, 100, 24.99, 1, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('LargeCapFund-1011', 'Bandhan Large Cap Fund', 'This LargeCap includes working examples that you can apply to your own projects. Purchase the LargeCap and get started today!', 'assets/images/products/LargeCap/largeCap-1011.png', 1, 100, 19.99, 1, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('LargeCapFund-1012', 'BOI Large Cap Fund', 'This LargeCap includes working examples that you can apply to your own projects. Purchase the LargeCap and get started today!', 'assets/images/products/LargeCap/largeCap-1012.png', 1, 100, 24.99, 1, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('LargeCapFund-1013', 'Canara Large Cap Fund', 'This LargeCap includes working examples that you can apply to your own projects. Purchase the LargeCap and get started today!', 'assets/images/products/LargeCap/largeCap-1013.png', 1, 100, 19.99, 1, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('LargeCapFund-1014', 'Edeilweiss Large Cap Fund', 'This LargeCap includes working examples that you can apply to your own projects. Purchase the LargeCap and get started today!', 'assets/images/products/LargeCap/largeCap-1014.png', 1, 100, 22.99, 1, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('LargeCapFund-1015', 'Invesco Large Cap Fund', 'This LargeCap includes working examples that you can apply to your own projects. Purchase the LargeCap and get started today!', 'assets/images/products/LargeCap/largeCap-1015.png', 1, 100, 22.99, 1, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('LargeCapFund-1016', 'Mahindra Large Cap Fund', 'This LargeCap includes working examples that you can apply to your own projects. Purchase the LargeCap and get started today!', 'assets/images/products/LargeCap/largeCap-1016.png', 1, 100, 27.99, 1, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('LargeCapFund-1017', 'PGIM Large Cap Fund', 'This LargeCap includes working examples that you can apply to your own projects. Purchase the LargeCap and get started today!', 'assets/images/products/LargeCap/largeCap-1017.png', 1, 100, 13.99, 1, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('LargeCapFund-1018', 'Tata Large Cap Fund', 'This LargeCap includes working examples that you can apply to your own projects. Purchase the LargeCap and get started today!', 'assets/images/products/LargeCap/largeCap-1018.png', 1, 100, 26.99, 1, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('LargeCapFund-1019', 'UTI Large Cap Fund', 'This LargeCap includes working examples that you can apply to your own projects. Purchase the LargeCap and get started today!', 'assets/images/products/LargeCap/largeCap-1019.png', 1, 100, 13.99, 1, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('LargeCapFund-1020', 'ITI Large Cap Fund', 'This LargeCap includes working examples that you can apply to your own projects. Purchase the LargeCap and get started today!', 'assets/images/products/LargeCap/largeCap-1020.png', 1, 100, 19.99, 1, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('LargeCapFund-1021', 'Motilal Large Cap Fund', 'This LargeCap includes working examples that you can apply to your own projects. Purchase the LargeCap and get started today!', 'assets/images/products/LargeCap/largeCap-1021.png', 1, 100, 18.99, 1, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('LargeCapFund-1022', 'DSP Large Cap Fund', 'This LargeCap includes working examples that you can apply to your own projects. Purchase the LargeCap and get started today!', 'assets/images/products/LargeCap/largeCap-1022.png', 1, 100, 26.99, 1, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('LargeCapFund-1023', 'LIC Large Cap Fund', 'This LargeCap includes working examples that you can apply to your own projects. Purchase the LargeCap and get started today!', 'assets/images/products/LargeCap/largeCap-1023.png', 1, 100, 22.99, 1, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('LargeCapFund-1024', 'ICICI Large Cap Fund', 'This LargeCap includes working examples that you can apply to your own projects. Purchase the LargeCap and get started today!', 'assets/images/products/LargeCap/largeCap-1024.png', 1, 100, 16.99, 1, NOW());



INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('GoldFundsFund-1000', 'SBI Gold Funds', 'Purchase the SBI Gold Funds and get started today!', 'assets/images/products/GoldFunds/GoldFunds-1000.png', 1, 100, 14.99, 1, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('GoldFundsFund-1001', 'Axis Gold Funds', 'Purchase the AXIS Gold Funds and get started today!', 'assets/images/products/GoldFunds/GoldFunds-1001.png', 1, 100, 20.99, 1, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('GoldFundsFund-1002', 'HSBC Gold Funds', 'Purchase the HSBC Gold Funds and get started today!', 'assets/images/products/GoldFunds/GoldFunds-1002.png', 1, 100, 14.99, 1, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('GoldFundsFund-1003', 'Kotak Gold Funds', 'Purchase the Kotak Gold Funds and get started today!', 'assets/images/products/GoldFunds/GoldFunds-1003.png', 1, 100, 13.99, 1, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('GoldFundsFund-1004', 'HDFC Gold Funds', 'Purchase the HDFC Gold Funds and get started today!', 'assets/images/products/GoldFunds/GoldFunds-1004.png', 1, 100, 18.99, 1, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('GoldFundsFund-1005', 'Aditya Birla Sun Life Gold Funds', 'Purchase the Aditya Birla Sun Life Gold Funds and get started today!', 'assets/images/products/GoldFunds/GoldFunds-1005.png', 1, 100, 23.99, 1, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('GoldFundsFund-1006', 'Invesco Gold Fund', 'Purchase the Invesco Gold Funds and get started today!', 'assets/images/products/GoldFunds/GoldFunds-1006.png', 1, 100, 14.99, 1, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('GoldFundsFund-1007', 'ICICI Gold Fund', 'Purchase the ICICI Gold Funds and get started today!', 'assets/images/products/GoldFunds/GoldFunds-1007.png', 1, 100, 16.99, 1, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('GoldFundsFund-1008', 'Quantum Gold Savings Fund', 'Purchase the Quantum Gold Funds and get started today!', 'assets/images/products/GoldFunds/GoldFunds-1008.png', 1, 100, 25.99, 1, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('GoldFundsFund-1008', 'Nippon Gold Savings Fund', 'Purchase the Nippon Gold Funds and get started today!', 'assets/images/products/GoldFunds/GoldFunds-1009.png', 1, 100, 25.99, 1, NOW());
